// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pymmnpuzgotcelpluwqx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5bW1ucHV6Z290Y2VscGx1d3F4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwODkzMTIsImV4cCI6MjA3MTY2NTMxMn0.4b94lOfCh-B_yzI1fMwKQRzoJ8kU2JrEd5VhvAPSyjA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});